### ISSUE TITLE
Demora en carga de imagenes

### ISSUE THREAD

**Issue by Carpani** [matiasf/luisa#1]
Hola. 
Se ha estado discutiendo bastante la demora en la carga de las imágenes.

Estuve probando bastante y al día hoy, la demora se da cuando se cargan las imágenes luego de enviar datos.

Allí hay un efecto "extraño" ... Las imágenes se transforman en puntos móviles.

No se podrá probar eliminar ese efecto y sólo cargar?

Saludos
FDO.

**Comment by matiasf** [comment]
Hola Fernando, que tal,

Se puede si aunque a nivel de experiencia de usuario entiendo que no es recomendable. 

Esa animacion es mostrada cuando el usuario apreta enviar y mientras el servidor no contesta las nuevas imagenes. Al no tener un refresco total de la pagina como la aplicacion anterior, se debe dar alguna señar al usuario de que se esta procesando su accion.

Si te das cuenta durante ese momento que es mientras se envia al server y vuelve desaparecen todos los controles ya que el usuario no debe tener interaccion en ese momento.

Talvez lo mejor es cambiar la animacion entera para que sea otro tipo de carga menos invasiba si es que no queda tan clara la interaccion.

Saludos,
Matías.
