### ISSUE TITLE
La imágenes largas se ven muy chicas.

### ISSUE THREAD

**Issue by Carpani** [matiasf/luisa#6]
En desktop, cuando sale una imagen que es muy larga, en vez de bajar las resantes o sea a un nuevo renglón, la deja allí.
Eso hace que salga muy chica, a veces, ilegible.

Va ejemplo:
![imagen](https://user-images.githubusercontent.com/753528/121198863-d748b900-c848-11eb-83ef-d291dd219c35.png)

**Comment by matiasf** [comment]
Aquí en la anterior se implementaba en un scroll lateral en la versión anterior, pero en movil ese scroll movía toda la aplicación, se implementa un scroll lateral sobre la imagen larga cuando sobrepasa la columna asignada.

En móvil este scroll es con el comportamiento touch, adjunto capturas de ejemplo.

Desktop
![image](https://user-images.githubusercontent.com/1846716/121605161-49282a80-ca22-11eb-9d8b-9b6f405939eb.png)

Movil
![image](https://user-images.githubusercontent.com/1846716/121605173-4fb6a200-ca22-11eb-887f-7f5e9aff04bf.png)

Desplegar para prueba.

**Comment by matiasf** [comment]
Verificado en testing se cierra issue
