### ISSUE TITLE
Campos de texto - celular

### ISSUE THREAD

**Issue by damianpintos** [matiasf/luisa#7]
Tenemos dos problemas en los campos de texto cuando ingresamos desde un celular:
 - comienza siempre en mayúscula (esto ya pasa en la versión anterior, pero sería una buena cosa arreglarlo)
 - habilita el autocompletar con valores ingresados anterioremente, esto es bastante pero bastante molesto.

**Comment by matiasf** [comment]
Se deshabilitan todos los controles de correcion y capitalizacion al campo por HTML, para validar en testing.

**Comment by matiasf** [comment]
No aplica a todos los dispositivos, volver a revisar.

**Comment by damianpintos** [comment]
yo lo daría por cerrado, con navegadores razonablemente actualizados parece funcionar bien.

**Comment by matiasf** [comment]
@damianpintos  en el próximo despliegue probamos de vuelta, hice un pequeño cambio que debería aplicar mucho mejor.

**Comment by matiasf** [comment]
Verificado en testing se cierra issue
